### ISSUE TITLE
Commit "Allow spawn-fcgi in the foreground" breaks windows builds

### ISSUE THREAD

**Issue by turkerali** [FastCGI-Archives/fcgi2#51]
When I try to build fcgi2 under windows with VS or mingw32, the build fails with the following error:

cgi-fcgi.c:21:10: fatal error: sys/wait.h: No such file or directory
   21 | #include <sys/wait.h>
      |          ^~~~~~~~~~~~

This is caused by the commit https://github.com/FastCGI-Archives/fcgi2/commit/3f131e797d90d40147ba990af54770dd0058fc66.
Without this commit, fcgi2 can be built with both VS and mingw32 without any errors.
